name: Build Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ghcr.io  
      DOCKER_USERNAME: ${{ secrets.GITHUB_ACTOR }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          registry: ${{ env.REPOSITORY }}
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.REPOSITORY }}/${{ env.DOCKER_USERNAME }}/library-app:latest
          push: true
